export const products = [
  {
    id: "product1",
    url: "https://www.linkpicture.com/q/Apple-Macbook-Air.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product2",
    url: "https://www.linkpicture.com/q/52a2df80-98ec-4e1b-9cfc-71a68d7575b3_1.4fbf81e4bfa56bc8feffa82b5b15ca83.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product3",
    url: "https://www.linkpicture.com/q/71fwbMm1NBL._AC_SL1500.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product4",
    url: "https://www.linkpicture.com/q/415ELavtbuL._SL1000.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product5",
    url: "https://www.linkpicture.com/q/airpods-max-hero-select-202011_FMT_WHH.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product6",
    url: "https://www.linkpicture.com/q/Apple-Ipad.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product7",
    url: "https://www.linkpicture.com/q/Apple-iPhone-11.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product8",
    url: "https://www.linkpicture.com/q/Apple-Smartwatch-Magic.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product9",
    url: "https://www.linkpicture.com/q/Apple-Watch-21-1.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product10",
    url: "https://www.linkpicture.com/q/apple_airpods.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product11",
    url: "https://www.linkpicture.com/q/Apple_homepod-mini-white.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product12",
    url: "https://www.linkpicture.com/q/apple_iPod_2A.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product13",
    url: "https://www.linkpicture.com/q/design-hero_2x.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product14",
    url: "https://www.linkpicture.com/q/in-resources-8fda3511-a61f-4c26-a4a0-f2bd37049878-images-productimages-29679821-500x500.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product15",
    url: "https://www.linkpicture.com/q/ipod-touch-select-blue-2019_GEO_US_FMT_WHH.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product16",
    url: "https://www.linkpicture.com/q/MQHX2.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product17",
    url: "https://www.linkpicture.com/q/MY812_VW_34FR-watch-44-alum-spacegray-nc-6s_VW_34FR_WF_CO_GEO_MY.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
  {
    id: "product18",
    url: "https://www.linkpicture.com/q/New-Apple-Mac-Mini.png",
    title: "Apple Macbook Pro",
    starRating: 5,
    netPrice: 499,
    mrp: 699,
    quantity: 0,
  },
];

export const storeAccesories = [
  {
    acName: " Apple Car",
    acValue: 2,
  },
  {
    acName: "Air port & wireless",
    acValue: 48,
  },
  {
    acName: " Cables & Docks",
    acValue: 14,
  },
  {
    acName: " Cases & Films",
    acValue: 15,
  },
  {
    acName: " Charging Devices",
    acValue: 23,
  },
  {
    acName: " Connected home",
    acValue: 1,
  },
  {
    acName: " Headphones",
    acValue: 95,
  },
];
export const brandData = [
  {
    brandName: "Apple",
    brandCount: 5,
  },
  {
    brandName: "LG",
    brandCount: 8,
  },
  {
    brandName: "Samsung",
    brandCount: 12,
  },
  {
    brandName: "Siemens",
    brandCount: 15,
  },
  {
    brandName: "Vivo",
    brandCount: 13,
  },
  {
    brandName: "Oppo",
    brandCount: 19,
  },
  {
    brandName: "RealMe",
    brandCount: 18,
  },
  {
    brandName: "Tecno",
    brandCount: 13,
  },
];
